# 
# Systems biology library for Ruby (Sylfy)
# Copyright (C) 2012-2013
#
# author: Natapol Pornputtapong <natapol@chalmers.se>
#
# Documentation: Natapol Pornputtapong (RDoc'd and embellished by William Webber)
#


module Dactyls
  
  class Node < MongoModel::Document
    
    self.collection_name = 'node'
    
    extend Dactyls::DocumentExtension
    
    def relations()
      Relation.where(:$or => [{:a => _id}, {:b => _id}])
    end
    
    def relateTos()
      relates = []
      Relation.where(:$or => [{:a => _id}, {:b => _id}]).each do |e|
        if e.a == _id
          relates.push(Node.find_one(:_id => e.b))
        else
          relates.push(Node.find_one(:_id => e.a))
        end
      end
      return relates
    end
    
  end
end
#!
#!=
#!~
#<=>
#==
#===
#=~
#[]
#[]=
#__id__
#__send__
#_create_callbacks
#_create_callbacks=
#_create_callbacks?
#_destroy_callbacks
#_destroy_callbacks=
#_destroy_callbacks?
#_find_callbacks
#_find_callbacks=
#_find_callbacks?
#_id
#_id=
#_id?
#_id_before_type_cast
#_id_change
#_id_changed?
#_id_was
#_id_will_change!
#_initialize_callbacks
#_initialize_callbacks=
#_initialize_callbacks?
#_save_callbacks
#_save_callbacks=
#_save_callbacks?
#_update_callbacks
#_update_callbacks=
#_update_callbacks?
#_validate_callbacks
#_validate_callbacks=
#_validate_callbacks?
#_validation_callbacks
#_validation_callbacks=
#_validation_callbacks?
#_validators
#_validators=
#_validators?
#acts_like?
#add_to_set!
#andand
#annotation
#annotation=
#annotation?
#annotation_before_type_cast
#annotation_change
#annotation_changed?
#annotation_was
#annotation_will_change!
#as_json
#assign_attributes
#associations
#attribute_aliases
#attribute_aliases?
#attribute_changed?
#attribute_method?
#attribute_method_matchers
#attribute_method_matchers?
#attribute_missing
#attribute_was
#attributes
#attributes=
#attributes_before_type_cast
#attributes_for_serialization
#blank?
#capture
#changed
#changed?
#changed_attributes
#changes
#class
#class_eval
#clone
#collection
#converse
#csmiles
#csmiles=
#csmiles?
#csmiles_before_type_cast
#csmiles_change
#csmiles_changed?
#csmiles_was
#csmiles_will_change!
#current_scope
#dataXref
#dataXref=
#dataXref?
#dataXref_before_type_cast
#dataXref_change
#dataXref_changed?
#dataXref_was
#dataXref_will_change!
#database
#dclone
#define_singleton_method
#delete
#destroy
#destroy_with_callbacks
#destroy_without_callbacks
#destroyed?
#display
#dont
#dup
#duplicable?
#embedded_documents
#enable_warnings
#enum_for
#eql?
#equal?
#errors
#extend
#formula
#formula=
#formula?
#formula_before_type_cast
#formula_change
#formula_changed?
#formula_was
#formula_will_change!
#freeze
#from_json
#frozen?
#generate_id
#hash
#id
#id=
#id?
#id_before_type_cast
#id_change
#id_changed?
#id_was
#id_will_change!
#inchi
#inchi=
#inchi?
#inchiKey
#inchiKey=
#inchiKey?
#inchiKey_before_type_cast
#inchiKey_change
#inchiKey_changed?
#inchiKey_was
#inchiKey_will_change!
#inchi_before_type_cast
#inchi_change
#inchi_changed?
#inchi_was
#inchi_will_change!
#include_root_in_json
#include_root_in_json=
#include_root_in_json?
#increase!
#increment!
#inherited
#initialize_with_record_status
#inspect
#instance_eval
#instance_exec
#instance_of?
#instance_values
#instance_variable_defined?
#instance_variable_get
#instance_variable_names
#instance_variable_set
#instance_variables
#invalid?
#is_a?
#isomer
#kind_of?
#load!
#locking_enabled?
#logger
#me
#method
#method_missing
#methods
#names
#names=
#names?
#names_before_type_cast
#names_change
#names_changed?
#names_was
#names_will_change!
#nested_attributes_options
#nested_attributes_options?
#new_record?
#nil?
#object_id
#original_attributes
#parent_document
#parent_document=
#participate
#per_page
#per_page=
#per_page?
#perform_validation
#persisted?
#pop!
#presence
#present?
#previous_changes
#private_methods
#properties
#protected_methods
#psych_to_yaml
#public_method
#public_methods
#public_send
#pull!
#pull_all!
#push!
#push_all!
#query_attribute
#quietly
#read_attribute
#read_attribute_before_type_cast
#read_attribute_for_serialization
#read_attribute_for_validation
#relateTos
#relations
#reload
#remove_instance_variable
#rename!
#reset__id!
#reset_annotation!
#reset_csmiles!
#reset_dataXref!
#reset_formula!
#reset_id!
#reset_inchi!
#reset_inchiKey!
#reset_names!
#reset_type!
#respond_to?
#respond_to_without_attributes?
#run_callbacks
#run_callbacks_with_embedded
#run_validations!
#sanitize_for_mass_assignment
#save
#save!
#send
#serializable_hash
#set!
#set_destroyed
#set_new_record
#shift!
#silence
#silence_stderr
#silence_stream
#silence_warnings
#singleton_class
#singleton_method
#singleton_methods
#stereomer
#suppress
#taint
#tainted?
#tap
#to_enum
#to_json
#to_json_with_active_support_encoder
#to_json_without_active_support_encoder
#to_key
#to_model
#to_mongo
#to_param
#to_partial_path
#to_query
#to_s
#to_yaml
#to_yaml_properties
#trust
#try
#try!
#type
#type=
#type?
#type_before_type_cast
#type_change
#type_changed?
#type_was
#type_will_change!
#unset!
#untaint
#untrust
#untrusted?
#update_attribute
#update_attributes
#update_attributes!
#valid?
#validates_absence_of
#validates_acceptance_of
#validates_confirmation_of
#validates_exclusion_of
#validates_format_of
#validates_inclusion_of
#validates_length_of
#validates_numericality_of
#validates_presence_of
#validates_size_of
#validates_with
#validation_context
#validation_context=
#with_warnings
#write_attribute